FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Pwr - Aplikacje mobilne
# Rezerwacja sal squasha



## All courts [/courts]

### Get all courts [GET]

+ Response 200 (application/json)

        [
             {
                "courtID": 5,
                "facilityID": 5,
                "courtNumber": 5
            }, {
                "courtID": 6,
                "facilityID": 6,
                "courtNumber": 6
            }, {
                "courtID": 7,
                "facilityID": 7,
                "courtNumber": 7
            }, {
                "courtID": 8,
                "facilityID": 8,
                "courtNumber": 8
            }
        ]


### Create new court [POST]

+ Request (application/json)

            {
                "courtID": 4,
                "facilityID": 4,
                "courtNumber": 4
            }

+ Response 201 (application/json)

    + Body

            {
                "courtID": 4,
                "facilityID": 4,
                "courtNumber": 4
            }


## Company [/company/{id}]
### Get company with specific ID [GET]

+ Parameters

    + id: 4 (number) - An unique identifier company
    
+ Response 200 (application/json)

    + Body

            {
                "companyID": 4, 
                "companyName": "Sport System", 
                "companyNIP": 6462933516, 
                "city": "Wroclaw", 
                "street": "Bagienna", 
                "buildingNumber": "1", 
                "postalCode": "51-522", 
                "localNumber": "1"
            }
     
            
# Group Users

## Users [/users/{id}]
### Get user with specific ID [GET]

+ Parameters

    + id: 4 (number) - An unique identifier of user

+ Response 200 (application/json)

    + Body

            {
                "userID": 4, 
                "userName": "Jan", 
                "userSurname": "Kowalski", 
                "userPassword": "sadfuh3iHSIFHASUIDFHiohiudsgu", 
                "userEmail": "a@a.com", 
                "userBirthDate": "12-04-2005", 
                "userPhoneNumber": "123345789"
            }


## All Users [/users/{?limit}]
A resource representing all of users in the system.

We have added the query URI template parameter - `limit`. This parameter is
used for limiting the number of results returned by some actions on this
resource. It does not affect every possible action of this resource, therefore
we will discuss it only at the particular action level below.

### Retrieve all Messages [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

+ Response 200 (application/json)

        [
            {
                "userID": 4, 
                "userName": "Jan", 
                "userSurname": "Kowalski", 
                "userPassword": "sadfuh3iHSIFHASUIDFHiohiudsgu", 
                "userEmail": "a@a.com", 
                "userBirthDate": "12-04-2005", 
                "userPhoneNumber": "123345789"
            },
            {
                "userID": 5, 
                "userName": "Marcin", 
                "userSurname": "Nowak", 
                "userPassword": "asdmiu3asdbaj", 
                "userEmail": "aaa@a.com", 
                "userBirthDate": "16-12-2005", 
                "userPhoneNumber": "879546123"
            },
            {
                "userID": 6, 
                "userName": "Piotr", 
                "userSurname": "Zbyniecki", 
                "userPassword": "ou98gbhi3", 
                "userEmail": "asd@a.com", 
                "userBirthDate": "12-04-2003", 
                "userPhoneNumber": "987459385"
            }
        ]

#Group Player

## Player [/player/{id}]
### Get player with specific ID [GET]
+ Parameters

    + id: 5 (number) - An unique identifier of player

+ Response 200 (application/json)

    + Body

            {
                "additionalPlayerID": 5, 
                "UserID": 6, 
                "reservationID": 10, 
                "IsCreator": [true], 
            }
## All Player [/player]

### Get all player [GET]

+ Response 200 (application/json)

        [
             {
                "additionalPlayerID": 5, 
                "UserID": 6, 
                "reservationID": 10, 
                "IsCreator": [true],
            }, {
                "additionalPlayerID": 7, 
                "UserID": 10, 
                "reservationID": 11, 
                "IsCreator": [false],
            }, {
                "additionalPlayerID": 9, 
                "UserID": 15, 
                "reservationID": 12, 
                "IsCreator": [true],
            }, {
                "additionalPlayerID": 11, 
                "UserID": 17, 
                "reservationID": 13, 
                "IsCreator": [true],
            }
        ]


### Create new player [POST]

+ Request (application/json)

            {
               "additionalPlayerID": 20, 
                "UserID": 30, 
                "reservationID": 14, 
                "IsCreator": [true],
            }

+ Response 201 (application/json)

    + Body

            {
               "additionalPlayerID": 20, 
                "UserID": 30, 
                "reservationID": 14, 
                "IsCreator": [true],
            }

#Group Facility

## All Facility [/facility]
A resource representing all of facilities in the system.
### Get all facility [GET]

+ Response 200 (application/json)

        [
             {
                "facilityID": 20, 
                "courtID": 30, 
                "companyID": 14, 
                "facilityName": "OSIR",
                "city": "Wrocław",
                "street": "Długa",
                "buildingNumber": "22a",
                "localNumber":" ",
                "postalCode":"55-158",
                "openingTime":"01:59:59.9999999",
                "closingTime":"23:59:59.9999999",
                "houerlyPrice": 50,
            }

## Facility [/facility/{id}]
### Get facility with specific ID [GET]
+ Parameters

    + id: 20 (number) - An unique identifier of facility

+ Response 200 (application/json)

    + Body

            {
               "facilityID": 20, 
                "courtID": 30, 
                "companyID": 14, 
                "facilityName": "OSIR",
                "city": "Wrocław",
                "street": "Długa",
                "buildingNumber": "22a",
                "localNumber":" ",
                "postalCode":"55-158",
                "openingTime":"01:59:59.9999999",
                "closingTime":"23:59:59.9999999",
                "houerlyPrice": 50,
            }

### Create new facility [POST]

+ Request (application/json)

            {
               "facilityID": 20, 
                "courtID": 30, 
                "companyID": 14, 
                "facilityName": "OSIR",
                "city": "Wrocław",
                "street": "Długa",
                "buildingNumber": "22a",
                "localNumber":" ",
                "postalCode":"55-158",
                "openingTime":"01:59:59.9999999",
                "closingTime":"23:59:59.9999999",
                "houerlyPrice": 50,
                
            }

+ Response 201 (application/json)

    + Body

            {
               "facilityID": 20, 
                "courtID": 30, 
                "companyID": 14, 
                "facilityName": "OSIR",
                "city": "Wrocław",
                "street": "Długa",
                "buildingNumber": "22a",
                "localNumber":" ",
                "postalCode":"55-158",
                "openingTime":"01:59:59.9999999",
                "closingTime":"23:59:59.9999999",
                "houerlyPrice": 50,
            }